import {
  ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid,
  Tooltip, ReferenceLine,
} from "recharts";
import { userOf } from "../constants.js";
import { fmtDur, pct } from "../utils.js";
import { useMetrics, CHART, weekDelta, latencySeries, buildEvents, EV_TEXT } from "../analytics.js";

function Delta({ cur, prev, suffix = "from last week" }) {
  if (!prev) return <div className="ad-delta flat">{cur} this week · no prior data</div>;
  const diff = Math.round(((cur - prev) / prev) * 100);
  if (diff === 0) return <div className="ad-delta flat">no change {suffix}</div>;
  return <div className={"ad-delta " + (diff > 0 ? "up" : "down")}>{diff > 0 ? "↑" : "↓"} {Math.abs(diff)}% {suffix}</div>;
}

export default function Dashboard({ tickets, goReview }) {
  const m = useMetrics(tickets);
  const pending = tickets.filter((t) => t.state === "review").length;
  const incoming = tickets.filter((t) => t.state === "inprocess").length;
  const dCreated = weekDelta(tickets, "created");
  const dDone = weekDelta(tickets, "doneAt");
  const lat = latencySeries(m);
  const events = buildEvents(tickets);
  const withinTarget = m.avgReview != null && m.avgReview <= 24 * 3600000;

  // rule funnel: what the AI produced vs what actually shipped
  const generated = m.passed + m.failed;
  const funnel = [
    { label: "Generated by AI", n: generated, sub: `across ${m.runsN} pipeline run${m.runsN === 1 ? "" : "s"}`, cls: "" },
    { label: "Passed sandbox pre-test", n: m.passed, sub: `${pct(m.passed, generated)} of generated`, cls: "" },
    { label: "Approved by moderators", n: m.approved, sub: `${pct(m.approved, m.passed)} of passed · ${m.rejected} rejected`, cls: "" },
    { label: "Deployed to filter list", n: m.live, sub: "from completed reviews only", cls: "deep" },
  ];
  const maxFun = Math.max(1, generated);

  // filter types: cosmetic (##selector) vs network (||domain^)
  const types = { cosmetic: { gen: 0, passed: 0, live: 0 }, network: { gen: 0, passed: 0, live: 0 } };
  tickets.forEach((t) =>
    (t.rules || []).forEach((r) => {
      const k = r.text.trim().startsWith("||") ? "network" : "cosmetic";
      types[k].gen++;
      if (r.status === "passed") types[k].passed++;
      if (r.decision === "approve" && t.state === "done") types[k].live++;
    })
  );

  const topSites = [...m.domains].sort((a, b) => b.reports - a.reports || b.live - a.live).slice(0, 6);

  return (
    <div className="ad-content">
      <div className="ad-pagehead">
        <div>
          <h1>Dashboard</h1>
          <p>Operational overview — detailed statistics live in Trend and Performance.</p>
        </div>
      </div>

      <div className="ad-stats" style={{ marginTop: 18 }}>
        <div className="ad-kpi k-deep">
          <div className="ad-statlabel">Total reports</div>
          <div className="ad-statnum">{m.total}</div>
          <Delta cur={dCreated.cur} prev={dCreated.prev} />
        </div>
        <button className="ad-kpi k-orange clickable" onClick={goReview} title="Open the review queue">
          <div className="ad-statlabel">Pending reviews</div>
          <div className="ad-statnum">{pending}</div>
          <div className="ad-delta flat">{incoming > 0 ? `${incoming} more incoming from the pipeline` : "queue fully synced"}</div>
        </button>
        <div className="ad-kpi k-green">
          <div className="ad-statlabel">Review SLA (≤ 24h)</div>
          <div className="ad-statnum">{m.sla == null ? "—" : m.sla + "%"}</div>
          <div className="ad-delta flat">{m.reviewsN} completed review{m.reviewsN === 1 ? "" : "s"}</div>
        </div>
        <div className="ad-kpi k-green">
          <div className="ad-statlabel">Rules deployed</div>
          <div className="ad-statnum">{m.live}</div>
          <Delta cur={dDone.cur} prev={dDone.prev} suffix="reports finished vs last week" />
        </div>
      </div>

      <div className="ad-grid2">
        <div className="ad-panel">
          <h3>Review latency per report (target: 24 hours)</h3>
          <div className="ad-chartbox">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={lat} margin={{ top: 8, right: 12, bottom: 0, left: -18 }}>
                <CartesianGrid stroke={CHART.grid} strokeDasharray="3 3" />
                <XAxis dataKey="name" tick={CHART.tick} tickLine={false} />
                <YAxis tick={CHART.tick} tickLine={false} unit="h" />
                <Tooltip formatter={(v) => [v + " h", "Review time"]} />
                <ReferenceLine y={24} stroke={CHART.orange} strokeDasharray="4 4" label={{ value: "target", fill: CHART.orange, fontSize: 11, position: "insideTopRight" }} />
                <Line type="monotone" dataKey="hours" stroke={CHART.deep} strokeWidth={2} dot={{ r: 3, fill: CHART.green, stroke: CHART.deep }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
          <div className="ad-caption">
            Current avg: <b>{fmtDur(m.avgReview)}</b>{m.avgReview != null ? (withinTarget ? " (within target)" : " (over target)") : ""}
          </div>
        </div>

        <div className="ad-panel">
          <h3>Rule funnel — AI output to deployment</h3>
          {funnel.map((f) => (
            <div className="ad-fun" key={f.label}>
              <div className="ad-funtop"><span>{f.label}</span><b>{f.n}</b></div>
              <div className="ad-funtrack"><span className={f.cls} style={{ width: (f.n / maxFun) * 100 + "%" }} /></div>
              <div className="ad-funsub">{f.sub}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="ad-grid3">
        <div className="ad-panel">
          <h3>Most reported websites</h3>
          <table className="ad-minitable">
            <thead><tr><th>Site</th><th>Reports</th><th>Rules live</th><th>Acceptance</th></tr></thead>
            <tbody>
              {topSites.map((d) => (
                <tr key={d.domain}>
                  <td>{d.domain}</td>
                  <td>{d.reports}</td>
                  <td><b>{d.live}</b></td>
                  <td>{pct(d.approved, d.approved + d.rejected)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="ad-panel">
          <h3>Rules by filter type</h3>
          {[
            { k: "cosmetic", label: "Cosmetic — hide elements (##…)" },
            { k: "network", label: "Network — block requests (||…^)" },
          ].map(({ k, label }) => {
            const v = types[k];
            return (
              <div className="ad-fun" key={k}>
                <div className="ad-funtop"><span>{label}</span><b>{v.live}/{v.gen} live</b></div>
                <div className="ad-funtrack"><span style={{ width: v.gen ? (v.live / v.gen) * 100 + "%" : 0 }} /></div>
                <div className="ad-funsub">{v.gen} generated · {v.passed} passed sandbox · {v.live} deployed</div>
              </div>
            );
          })}
          <div className="ad-funsub" style={{ marginTop: 8 }}>
            Cosmetic rules clean the page; network rules stop the ad request itself.
          </div>
        </div>

        <div className="ad-panel">
          <h3>Recent activity</h3>
          <ul className="ad-feed">
            {events.map((e, i) => (
              <li key={i}>
                <span className="ad-feedtime">{new Date(e.ts).toLocaleString("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</span>
                <span className="ad-feedtext">
                  <b>{e.name}</b> {EV_TEXT[e.kind]}{e.by ? ` ${userOf(e.by)?.name}` : ""}{e.extra ? ` — ${e.extra}` : ""}
                </span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
